### ISSUE TITLE
Unable to add cards

### ISSUE THREAD

**Issue by jojoharry16** [nmaggioni/Kanbanion#22]
Love the simplicity this app is going for, but mine... isn't working
I followed the instructions in the README file, and the program opened, but the `+` button does nothing

**OS:** Linux > Debian > Pop!_OS > KDE Plasma

**Comment by nmaggioni** [comment]
Thanks for the report, try the [latest release](https://github.com/nmaggioni/Kanbanion/releases/tag/v1.1.0). Since this project is quite old I've updated most dependencies and fixed some small bugs with dialogs and buttons.

Electron's releases have also grown in size considerably, I had to switch to 7zip to get a reasonable compression rate with multiplatform support.
